version: "2"

services:
  # Behat
  behat:
    hostname: behat
    #image: docksal/behat
    build: ..
    volumes:
      - .:/src
    # Run a built-in web server for access to HTML reports
    ports:
     - 8000:8000
    entrypoint: "php -S 0.0.0.0:8000"
