#!/usr/bin/env bash

set -e  # Fail on errors

# Run behat commands in a running behat container
# Have to use `docker exec`, since `docker-compose run` won't work on Windows (TODO: is this still true?)
docker exec $(docker-compose ps -q behat) behat --colors "$@"
